jobs:
  test:
    executor:
      name: node/default
      tag: '15'
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
orbs:
  node: circleci/node@4.1
version: 2.1
workflows:
  test_my_app:
    jobs:
      - test